# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [14]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")

In [15]:
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [18]:
users.info

<bound method DataFrame.info of      user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]>

In [16]:
users.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [19]:
users['occupation'].dtype

dtype('O')

### Step 4. Discover what is the mean age per occupation

In [20]:
users.groupby('occupation')['age'].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

In [12]:
users.columns

Index(['user_id|age|gender|occupation|zip_code'], dtype='object')

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [21]:
users['is_male'] = users['gender'] == 'M'

In [23]:
users.head()

   user_id  age gender  occupation zip_code  is_male
0        1   24      M  technician    85711     True
1        2   53      F       other    94043    False
2        3   23      M      writer    32067     True
3        4   24      M  technician    43537     True
4        5   33      F       other    15213    False

In [28]:
users.groupby('occupation')['is_male'].count().sort_values(ascending=False)

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: is_male, dtype: int64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [32]:
users.groupby('occupation')['age'].min()

occupation
administrator    21
artist           19
doctor           28
educator         23
engineer         22
entertainment    15
executive        22
healthcare       22
homemaker        20
lawyer           21
librarian        23
marketing        24
none             11
other            13
programmer       20
retired          51
salesman         18
scientist        23
student           7
technician       21
writer           18
Name: age, dtype: int64

In [33]:
users.groupby('occupation')['age'].max()

occupation
administrator    70
artist           48
doctor           64
educator         63
engineer         70
entertainment    50
executive        69
healthcare       62
homemaker        50
lawyer           53
librarian        69
marketing        55
none             55
other            64
programmer       63
retired          73
salesman         66
scientist        55
student          42
technician       55
writer           60
Name: age, dtype: int64

### Step 7. For each combination of occupation and gender, calculate the mean age

In [36]:
users.groupby(['occupation','gender'])['age'].mean().unstack()

gender                 F          M
occupation
administrator  40.638889  37.162791
artist         30.307692  32.333333
doctor               NaN  43.571429
educator       39.115385  43.101449
engineer       29.500000  36.600000
entertainment  31.000000  29.000000
executive      44.000000  38.172414
healthcare     39.818182  45.400000
homemaker      34.166667  23.000000
lawyer         39.500000  36.200000
librarian      40.000000  40.000000
marketing      37.200000  37.875000
none           36.500000  18.600000
other          35.472222  34.028986
programmer     32.166667  33.216667
retired        70.000000  62.538462
salesman       27.000000  38.555556
scientist      28.333333  36.321429
student        20.750000  22.669118
technician     38.000000  32.961538
writer         37.631579  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [50]:
users.groupby(['occupation','gender']).size().groupby(level=0).apply(lambda x: 100 * x/x.sum()).unstack()

gender                               F           M
occupation    occupation
administrator administrator  45.569620   54.430380
artist        artist         46.428571   53.571429
doctor        doctor               NaN  100.000000
educator      educator       27.368421   72.631579
engineer      engineer        2.985075   97.014925
entertainment entertainment  11.111111   88.888889
executive     executive       9.375000   90.625000
healthcare    healthcare     68.750000   31.250000
homemaker     homemaker      85.714286   14.285714
lawyer        lawyer         16.666667   83.333333
librarian     librarian      56.862745   43.137255
marketing     marketing      38.461538   61.538462
none          none           44.444444   55.555556
other         other          34.285714   65.714286
programmer    programmer      9.090909   90.909091
retired       retired         7.142857   92.857143
salesman      salesman       25.000000   75.000000
scientist     scientist       9.677419   90.322581
student       student        30.612245   69.387755
technician    technician      3.703704   96.296296
writer        writer         42.222222   57.777778