# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [25]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'

### Step 3. Assign it to a variable called wine

In [27]:
wine = pd.read_csv(url)

In [28]:
wine.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [29]:
colms_to_drop = [0,3,6,8,10,12,13]

In [30]:
wine = wine.drop(wine.columns[colms_to_drop],axis=1)

In [39]:
wine.head()

   14.23  1.71  15.6  127  3.06  2.29  1.04
0  13.20  1.78  11.2  100  2.76  1.28  1.05
1  13.16  2.36  18.6  101  3.24  2.81  1.03
2  14.37  1.95  16.8  113  3.49  2.18  0.86
3  13.24  2.59  21.0  118  2.69  1.82  1.04
4  14.20  1.76  15.2  112  3.39  1.97  1.05

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [40]:
len(wine.columns)

7

In [88]:
wine1 = wine.rename(columns={'14.23':'alcohol','1.71':'malic_acid','15.6':'alcalinity_of_ash',	'127':'magnesium',	'3.06':'flavanoids','2.29':'proanthocyanins','1.04':'hue'})

In [89]:
wine1

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,13.20,1.78,11.2,100,2.76,1.28,1.05
1,13.16,2.36,18.6,101,3.24,2.81,1.03
2,14.37,1.95,16.8,113,3.49,2.18,0.86
3,13.24,2.59,21.0,118,2.69,1.82,1.04
4,14.20,1.76,15.2,112,3.39,1.97,1.05
...,...,...,...,...,...,...,...
172,13.71,5.65,20.5,95,0.61,1.06,0.64
173,13.40,3.91,23.0,102,0.75,1.41,0.70
174,13.27,4.28,20.0,120,0.69,1.35,0.59
175,13.17,2.59,20.0,120,0.68,1.46,0.60
176,14.13,4.10,24.5,96,0.76,1.35,0.61

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [90]:
wine1.iloc[0:3,wine1.columns.get_loc('alcohol')] = np.nan

In [91]:
wine1.columns

Index(['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids',
       'proanthocyanins', 'hue'],
      dtype='object')

In [92]:
wine1.head(7)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100,2.76,1.28,1.05
1,NaN,2.36,18.6,101,3.24,2.81,1.03
2,NaN,1.95,16.8,113,3.49,2.18,0.86
3,13.24,2.59,21.0,118,2.69,1.82,1.04
4,14.20,1.76,15.2,112,3.39,1.97,1.05
5,14.39,1.87,14.6,96,2.52,1.98,1.02
6,14.06,2.15,17.6,121,2.51,1.25,1.06

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [93]:
wine1.iloc[2:4,wine1.columns.get_loc('magnesium')] = np.nan

In [94]:
wine1.head(7)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100.0,2.76,1.28,1.05
1,NaN,2.36,18.6,101.0,3.24,2.81,1.03
2,NaN,1.95,16.8,NaN,3.49,2.18,0.86
3,13.24,2.59,21.0,NaN,2.69,1.82,1.04
4,14.20,1.76,15.2,112.0,3.39,1.97,1.05
5,14.39,1.87,14.6,96.0,2.52,1.98,1.02
6,14.06,2.15,17.6,121.0,2.51,1.25,1.06

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [95]:
wine1.fillna({'alcohol': 10, 'magnesium': 100}, inplace=True)

In [96]:
wine1.head(7)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.78,11.2,100.0,2.76,1.28,1.05
1,10.00,2.36,18.6,101.0,3.24,2.81,1.03
2,10.00,1.95,16.8,100.0,3.49,2.18,0.86
3,13.24,2.59,21.0,100.0,2.69,1.82,1.04
4,14.20,1.76,15.2,112.0,3.39,1.97,1.05
5,14.39,1.87,14.6,96.0,2.52,1.98,1.02
6,14.06,2.15,17.6,121.0,2.51,1.25,1.06

### Step 9. Count the number of missing values

In [97]:
wine1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   alcohol            177 non-null    float64
 1   malic_acid         177 non-null    float64
 2   alcalinity_of_ash  177 non-null    float64
 3   magnesium          177 non-null    float64
 4   flavanoids         177 non-null    float64
 5   proanthocyanins    177 non-null    float64
 6   hue                177 non-null    float64
dtypes: float64(7)
memory usage: 9.8 KB

In [98]:
wine1.isna().sum().sum()

np.int64(0)

### Step 10.  Create an array of 10 random numbers up until 10

In [99]:
a = np.random.randint(0, 10, size=10)

In [100]:
a

array([6, 7, 1, 6, 8, 5, 0, 6, 2, 4])

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [101]:
wine1.loc[a,['alcohol','magnesium']] = np.nan

In [102]:
wine1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   alcohol            169 non-null    float64
 1   malic_acid         177 non-null    float64
 2   alcalinity_of_ash  177 non-null    float64
 3   magnesium          169 non-null    float64
 4   flavanoids         177 non-null    float64
 5   proanthocyanins    177 non-null    float64
 6   hue                177 non-null    float64
dtypes: float64(7)
memory usage: 9.8 KB

### Step 12.  How many missing values do we have?

In [103]:
wine1.isna().sum().sum()

np.int64(16)

### Step 13. Delete the rows that contain missing values

In [104]:
wine2 = wine1.dropna()

In [105]:
wine2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 169 entries, 3 to 176
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   alcohol            169 non-null    float64
 1   malic_acid         169 non-null    float64
 2   alcalinity_of_ash  169 non-null    float64
 3   magnesium          169 non-null    float64
 4   flavanoids         169 non-null    float64
 5   proanthocyanins    169 non-null    float64
 6   hue                169 non-null    float64
dtypes: float64(7)
memory usage: 10.6 KB

In [106]:
wine2.isna().sum().sum()

np.int64(0)

### Step 14. Print only the non-null values in alcohol

In [107]:
wine2['alcohol'].notna()

3      True
9      True
10     True
11     True
12     True
       ...
172    True
173    True
174    True
175    True
176    True
Name: alcohol, Length: 169, dtype: bool

### Step 15.  Reset the index, so it starts with 0 again

In [108]:
wine2.reset_index(drop=True,inplace=True)

In [109]:
wine2.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,13.24,2.59,21.0,100.0,2.69,1.82,1.04
1,14.10,2.16,18.0,105.0,3.32,2.38,1.25
2,14.12,1.48,16.8,95.0,2.43,1.57,1.17
3,13.75,1.73,16.0,89.0,2.76,1.81,1.15
4,14.75,1.73,11.4,91.0,3.69,2.81,1.25

### BONUS: Create your own question and answer it.

delete only the rows where alcohol is missing, but keep rows where magnesium is NaN

In [110]:
wine3 = wine1.dropna(subset=['alcohol'])

In [111]:
wine3.isna().sum().sum()

np.int64(0)

In [115]:
wine3['magnesium'].isna().sum()

np.int64(0)

In [116]:
wine1[wine1['magnesium'].isna()]

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,NaN,2.76,1.28,1.05
1,NaN,2.36,18.6,NaN,3.24,2.81,1.03
2,NaN,1.95,16.8,NaN,3.49,2.18,0.86
4,NaN,1.76,15.2,NaN,3.39,1.97,1.05
5,NaN,1.87,14.6,NaN,2.52,1.98,1.02
6,NaN,2.15,17.6,NaN,2.51,1.25,1.06
7,NaN,1.64,14.0,NaN,2.98,1.98,1.08
8,NaN,1.35,16.0,NaN,3.15,1.85,1.01